### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#114]
**Roadmap**

- [x] Implementation of authentication and user accounts using Firebase authentication and Realtime database.
- [ ] Make the Home Activity as a news feed fetching data from all the Facebook pages associated with IIT Patna.
- [ ] A video feed activity fetching all the videos from IIT Patna channels.
- [x] Timetable 
- [ ] Attendance.

**Comment by fayaz07** [comment]
Firebase auth, how it should be I mean fb auth, gmail auth, phone auth??

**Comment by fayaz07** [comment]
Firebase auth, how it should be I mean fb auth, gmail auth, phone auth??

**Comment by sheetal-g9** [comment]
Additional Features:
1. Explore: description of clubs and other college departments 
2. Hostel Wise Mess Menu 
3. Maps
4. Quick Links
