### ISSUE TITLE
Migrate to Architecture components in Coding Calendar

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#48]
There is no specific architechture of the application right now. We should develop new modules using MVVM architecture and refactor CodingCalendar later to MVVM.

- [x] Create ViewModels
- [x] Wrap data into LiveData
- [x] Migrate to Room
- [x] Write ViewModel tests. 

Not a current priority but certainly for the future.

**Comment by dr0pdb** [comment]
Done.
