### ISSUE TITLE
Roadmap of the project

### ISSUE THREAD

**Issue by dr0pdb** [Njack-IITP/IITP-Connect#72]
Since there isn't a proper place to add the detailed Roadmap of the project and discuss it. I'll add it here.
Here are the next few steps that we have to take:

- [ ] Migrate to ROOM in Coding calendar (#59 )
We cannot use two databases at the same time and it would be very time-consuming to use Content providers for other features also. So the best solution would be to refactor Coding calendar to use ROOM.

- [ ] Create the database for Attendance manager.(#15 )

- [ ] Create the UI for Attendance manager(#71 )

Will keep on adding as they come.

@mayank8318 @arundhati24

**Comment by arundhatigupta** [comment]
Let's use wiki for roadmap and features
@srv-twry @mayank8318

**Comment by arundhatigupta** [comment]
That way it would become easier for anyone checking out this project to understand several features.

**Comment by dr0pdb** [comment]
I understand but setting up wiki takes time and we need to have features first before adding a wiki about it.
Let's use this temporarily and then move to wiki when we have sufficient number of features i.e. atleast three.
